name: MacOS CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build-gcc12:
    name: GNU GCC 12
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Build mockturtle
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_CXX_COMPILER=$(which g++-12) -DMOCKTURTLE_TEST=ON ..
        make run_tests
    - name: Run tests
      run: |
        cd build
        ./test/run_tests "~[quality]"
  build-clang14:
    name: Clang 14
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Build mockturtle
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DMOCKTURTLE_TEST=ON ..
        make run_tests
    - name: Run tests
      run: |
        cd build
        ./test/run_tests "~[quality]"
  build-clang15:
    name: Clang 15
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Build mockturtle
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_CXX_COMPILER=$(brew --prefix llvm@15)/bin/clang++ -DMOCKTURTLE_TEST=ON ..
        make run_tests
    - name: Run tests
      run: |
        cd build
        ./test/run_tests "~[quality]"
