name: Windows CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: windows-latest
    name: Visual Studio

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Create build directory
      run: mkdir build
    - name: Run CMake
      run: cmake -G "Visual Studio 16 2019" -DMOCKTURTLE_TEST=ON ..
      working-directory: ./build
    - name: ls
      run: |
        ls
      working-directory: ./build
      shell: cmd
    - name: Cat
      run: |
        cat mockturtle.sln
      working-directory: ./build
      shell: cmd
    - name: List targets
      run: |
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" mockturtle.sln -targets
      working-directory: ./build
      shell: cmd
    - name: Build mockturtle
      run: |
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" mockturtle.sln -t:run_tests
      working-directory: ./build
      shell: cmd
    - name: Run tests
      run: |
        cd build
        .\test\Debug\run_tests "~[quality]"
